services:
  postgres:
    image: postgres:16-alpine
    container_name: compex-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: compex
      POSTGRES_PASSWORD: jArZOhwQJmbd4HtKrOn5fuBsOjJ6
      POSTGRES_DB: compex
    ports:
      - "55432:5432"
    volumes:
      - compex_postgres_data:/var/lib/postgresql/data

volumes:
  compex_postgres_data:
