ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "socialName" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "nickname" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "sex" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "photoUrl" TEXT;
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "birthDate" TIMESTAMP(3);
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "memberType" TEXT NOT NULL DEFAULT 'TORCEDOR';
ALTER TABLE "Member" ADD COLUMN IF NOT EXISTS "selectedSports" JSONB;
